CREATE TABLE TB_COMMENT (
    COMMENT_ID NUMBER NOT NULL,
    GROUP_ID NUMBER,
    USER_ID NUMBER,
    CONTENT VARCHAR2(500 BYTE) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_COMMENT PRIMARY KEY (COMMENT_ID)
);
