CREATE TABLE TB_DIARYQUESTION
	(
        DQ_ID           NUMBER(3, 0)    NOT NULL,   -- 그룹 아이디
		DQ_CONTENT		NVARCHAR2(50)   NOT NULL    -- 사용자 아이디
	);
    
CREATE UNIQUE INDEX IX1_DIARYQUESTION ON TB_DIARYQUESTION (DQ_ID);

/*
SELECT * FROM TB_DIARYQUESTION;
*/
