CREATE TABLE TB_GROUPLIST
	(
        GROUP_ID        NUMBER(20, 0)   NOT NULL,   -- 그룹 아이디
		GROUPNAME		NVARCHAR2(10)	NOT NULL    -- 그룹 이름
	);

CREATE UNIQUE INDEX IX1_GROUPLIST ON TB_GROUPLIST (GROUP_ID);

/*
INSERT INTO TB_GROUPLIST   (GROUP_ID, GROUPNAME)
            VALUES         (1, '태우와 아이들');
INSERT INTO TB_GROUPLIST   (GROUP_ID, GROUPNAME)
            VALUES         (2, '눈에 확 띄잖아');

SELECT * FROM TB_GROUPLIST;
*/
