CREATE TABLE TB_GROUPUSERLIST
	(
        GROUP_ID    NUMBER(20, 0)   NOT NULL,   -- 그룹 아이디
		USER_ID		NUMBER(20, 0)	NOT NULL    -- 사용자 아이디
	);

/*
INSERT INTO TB_GROUPUSERLIST   (GROUP_ID, USER_ID)
            VALUES              (1, 1);
INSERT INTO TB_GROUPUSERLIST   (GROUP_ID, USER_ID)
            VALUES              (1, 2);
INSERT INTO TB_GROUPUSERLIST   (GROUP_ID, USER_ID)
            VALUES              (1, 3);
INSERT INTO TB_GROUPUSERLIST   (GROUP_ID, USER_ID)
            VALUES              (2, 2);
INSERT INTO TB_GROUPUSERLIST   (GROUP_ID, USER_ID)
            VALUES              (2, 4);

SELECT * FROM TB_GROUPUSERLIST;
SELECT * FROM TB_GROUPUSERLIST WHERE GROUP_ID = 1;
SELECT * FROM TB_GROUPUSERLIST WHERE USER_ID = 2;
*/
