CREATE OR REPLACE PROCEDURE SP_HEALTH_CUD
(
	iJobStatus			IN VARCHAR2,				-- 작업상태
	iHEALTH_DATE        IN DATE,					-- 건강기록 날짜
	iUSER_ID            IN NUMBER,					-- 사용자 아이디
	iGOAL_WATER         IN CHAR,					-- 목표 음수량
	iACHIEVED_WATER     IN CHAR,					-- 달성 음수량
	iTYPE_EXERCISE      IN NVARCHAR2,				-- 운동종류
	iGOAL_EXERCISE      IN CHAR,					-- 목표 운동기록
	iACHIEVED_EXERCISE  IN CHAR,					-- 달성 운동기록
	iBEDTIME            IN NVARCHAR2,				-- 취침시간
	iWAKETIME           IN NVARCHAR2				-- 기상시간
)
IS
BEGIN
	DECLARE
		mCount	int;

	BEGIN
		SELECT	COUNT(*) INTO	mCount
		FROM	TB_HEALTH
		WHERE	HEALTH_DATE	= iHEALTH_DATE	AND
				USER_ID		= iUSER_ID;

		IF iJobStatus = 'DELETE' THEN
			DELETE FROM TB_HEALTH
			WHERE	HEALTH_DATE	= iHEALTH_DATE
					AND USER_ID	= iUSER_ID;
					
		ELSIF mCount = 0 THEN
			IF iJobStatus = 'WATER' THEN
				INSERT INTO TB_HEALTH (HEALTH_DATE, USER_ID, GOAL_WATER, ACHIEVED_WATER)
				VALUES (iHEALTH_DATE, iUSER_ID, iGOAL_WATER, iACHIEVED_WATER);
			ELSIF iJobStatus = 'EXERCISE' THEN
				INSERT INTO TB_HEALTH (HEALTH_DATE, USER_ID, TYPE_EXERCISE, GOAL_EXERCISE, ACHIEVED_EXERCISE)
				VALUES (iHEALTH_DATE, iUSER_ID, iTYPE_EXERCISE, iGOAL_EXERCISE, iACHIEVED_EXERCISE);
			ELSIF iJobStatus = 'SLEEP' THEN
				INSERT INTO TB_HEALTH (HEALTH_DATE, USER_ID, BEDTIME, WAKETIME)
				VALUES (iHEALTH_DATE, iUSER_ID, iBEDTIME, iWAKETIME);
			END IF;				
		ELSE
			IF iJobStatus = 'WATER' THEN
				UPDATE	TB_HEALTH
				SET		GOAL_WATER			= iGOAL_WATER,
						ACHIEVED_WATER		= iACHIEVED_WATER
				WHERE	HEALTH_DATE			= iHEALTH_DATE
						AND USER_ID			= iUSER_ID;
			ELSIF iJobStatus = 'EXERCISE' THEN
				UPDATE	TB_HEALTH
				SET		TYPE_EXERCISE		= iTYPE_EXERCISE,
						GOAL_EXERCISE		= iGOAL_EXERCISE,
						ACHIEVED_EXERCISE	= iACHIEVED_EXERCISE
				WHERE	HEALTH_DATE			= iHEALTH_DATE
						AND USER_ID			= iUSER_ID;
			ELSIF iJobStatus = 'SLEEP' THEN
				UPDATE	TB_HEALTH
				SET		BEDTIME				= iBEDTIME,
						WAKETIME			= iWAKETIME
				WHERE	HEALTH_DATE			= iHEALTH_DATE
						AND USER_ID			= iUSER_ID;
			END IF;				
		END IF;
	END;	
END SP_HEALTH_CUD;
