create or replace PROCEDURE SP_MYGROUP_R
(
	iUserId	IN	int,				-- 유저번호
	oCur		OUT	SYS_REFCURSOR	-- 결과 반환용 커서
)
IS
BEGIN
	OPEN oCur FOR
	SELECT	a.GROUP_ID,
			(SELECT b.GROUPNAME FROM TB_GROUPLIST b WHERE a.GROUP_ID = b.GROUP_ID) AS GROUPNAME
	FROM	TB_GROUPUSERLIST a
	WHERE	a.USER_ID = iUserId
	ORDER BY a.GROUP_ID;
END SP_MYGROUP_R;