CREATE OR REPLACE PROCEDURE SP_USERS_RESETPWD
(
    iEMAIL		IN	VARCHAR2,	    -- 이메일
    iPASSWORD   IN	VARCHAR2		-- 비밀번호
)
IS
BEGIN
	UPDATE TB_USERS
	SET	    PASSWORD	= iPASSWORD
	WHERE   EMAIL = iEMAIL;

	RETURN;
END SP_USERS_RESETPWD;